[package]
name = "circus-crx-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
case_insensitive_hashmap = "1"
clap = { version = "4", features = ["derive"] }
fdeflate = "0.3"
lazy_static = "1.5"
png = "0.17"
zstd = "0.13"
